'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

def fibo(liz,x):
	i=1;k=0
	j=2
	liz.append(i)
	liz.append(j)
	while i+j < x:
		k=i+j
		liz.append(k)
		i=j
		j=k
	return liz
def som(liz):
	i=0
	for j in liz:
		if j%2==0:
			i+=j
	return i		
lim=[]
print "enter the range of the numbers from zero "
edge=input()
lim=fibo(lim,edge)
l=som(lim)
print l
